# Source: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: santileira
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_timezone: America/Buenos_Aires